name: Release prebuilt binaries from URL
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository for which to push the release.'
        required: true
      release-tag-prefix:
        description: 'The prefix to use for the release tag. Use the Engine version, or leave empty if latest version. If a version is supplied, a slash has to be appended, e.g.: v1.2.2/'

jobs:
  build:
    name: Release prebuilt binaries
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            name: "Ubuntu Latest"
    steps:
      - name: Get Binaries
        shell: bash
        run: |
          wget https://pragma-engine.com/share/github/${{ inputs.repository }}/binaries_windows64.zip
          wget https://pragma-engine.com/share/github/${{ inputs.repository }}/binaries_linux64.tar.gz

      - name: Update Nightly Tag
        uses: rickstaa/action-create-tag@v1.3.9
        continue-on-error: true
        with:
          tag: "${{ inputs.release-tag-prefix }}${{ inputs.repository }}"
          force_push_tag: true

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "binaries_linux64.tar.gz,binaries_windows64.zip"
          body: "Automatically generated binaries."
          commit: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ inputs.release-tag-prefix }}${{ inputs.repository }}"
          replacesArtifacts: true
          allowUpdates: true
          
